DROP PROCEDURe CISDB.SPCISSELASSET;

GRANT EXECUTE ON PROCEDURE CISDB.SPCISSELASSET TO CIS_PORTAL_USER;

create procedure CISDB.SPCISSELASSET()
BEGIN
DECLARE CUR CURSOR FOR SELECT 
	FIIDASSET 'id',
	FIIDLEDGER idLedger,
	FIIDASSETTYPE idAssetType,
	FCDESCRIPTION description,
	FCBRAND brand,
	FCMODEL model,
	FCSERIALNUMBER serialNumber,
	FIIDMATERIAL idMaterial,
	FCCOLOR color,
	FCSUPPLIER supplier,
	FCGENERALMANAGER generalManager,
	FCDIRECTLYRESPONSIBLE directlyResponsible,
	FITAG tag,
	FCBILL bill,
	FDBILLINGDATE billDate,
	FCLOCATION location,
	FDUSEDATE useDate,
	FNPRICE price,
	FCGENERALLOCATION generalLocation, 
	FCSECURE secure,
	FDREGISTERDATE registerDate,
	FDLASTUPDATE lastUpdate
FROM CISDB.TACISASSET;
END