GRANT SELECT, INSERT, UPDATE, DELETE ON ICSDB.TAICSUSER TO ICS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ICSDB.TAICSASSET TO ICS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON ICSDB.CTICSLEDGER TO ICS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON ICSDB.CTICSPROPERTY TO ICS_PORTAL_USER;