GRANT SELECT, INSERT, UPDATE, DELETE ON CISDB.TACISUSER TO CIS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CISDB.TACISASSET TO CIS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CISDB.CTCISASSETTYPE TO CIS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CISDB.CTCISMATERIAL TO CIS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON CISDB.CTCISCOLOR TO CIS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON CISDB.CTCISLEDGER TO CIS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON CISDB.CTCISPROPERTY TO CIS_PORTAL_USER;