--DROP DATABASE ICSDB;
CREATE DATABASE ICSDB;

--DROP TABLE ICSDB.TAICSUSER;

CREATE TABLE ICSDB.TAICSUSER 
( 
  FIIDUSER INT(10) NOT NULL AUTO_INCREMENT
, FCUSERNAME VARCHAR(50) NOT NULL  
, FCPASSWORD VARCHAR(100) NOT NULL 
, FCAUTHORITY VARCHAR(50) NOT NULL 
, FCENABLED ENUM('1','0') NOT NULL  
, FCNAME VARCHAR(50) NOT NULL  
, FCLASTNAME VARCHAR(50)  
, FCSEX ENUM('M','F')  
, FDBIRTH DATE  
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDUSER ) );

CREATE UNIQUE INDEX TAICSUSER_INDEX1 ON ICSDB.TAICSUSER ( FIIDUSER ASC);

CREATE UNIQUE INDEX TAICSUSER_INDEX2 ON ICSDB.TAICSUSER ( FCUSERNAME ASC);

--DROP TABLE ICSDB.CTICSLEDGER;

CREATE TABLE ICSDB.CTICSLEDGER 
( 
  FIIDLEDGER INT(10) NOT NULL 
, FCSUBCLASS VARCHAR(2) NOT NULL 
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDLEDGER, FCSUBCLASS ) );

CREATE INDEX CTICSLEDGER_INDEX1 ON ICSDB.CTICSLEDGER ( FIIDLEDGER ASC, FCSUBCLASS ASC);

--DROP TABLE ICSDB.CTICSPROPERTY;

CREATE TABLE ICSDB.CTICSPROPERTY 
( 
  FCIDPROPERTY VARCHAR(30) NOT NULL
, FCVALUE VARCHAR(50) NOT NULL
, FCDEFAULT VARCHAR(50) NOT NULL 
, CONSTRAINT PRIMARY KEY ( FCIDPROPERTY ) );

CREATE INDEX CTICSPROPERTY_INDEX1 ON ICSDB.CTICSPROPERTY ( FCIDPROPERTY ASC);

--DROP TABLE ICSDB.TAICSASSET;

CREATE TABLE ICSDB.TAICSASSET 
( 
  FIIDASSET BIGINT(19) NOT NULL AUTO_INCREMENT
, FIIDLEDGER INT(10) NOT NULL 
, FCSUBCLASS VARCHAR(2) NOT NULL 
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FCBRAND VARCHAR(100) NULL DEFAULT 'Sin marca' 
, FCMODEL VARCHAR(100) NULL DEFAULT 'Sin modelo' 
, FCSERIALNUMBER VARCHAR(100) NULL DEFAULT 'Sin numero de serie' 
, FCMATERIAL VARCHAR(100) NULL 
, FCCOLOR VARCHAR(100) NULL 
, FCSUPPLIER VARCHAR(100) NULL DEFAULT 'Proveedor no identificado' 
, FCGENERALMANAGER VARCHAR(100) NULL 
, FCDIRECTLYRESPONSIBLE VARCHAR(100) NULL 
, FITAG BIGINT(19) NOT NULL 
, FCBILL VARCHAR(100) NULL DEFAULT 'Sin factura' 
, FDBILLINGDATE DATE NULL DEFAULT '2015-06-01' 
, FCLOCATION VARCHAR(100) NULL 
, FDUSEDATE DATE NULL DEFAULT '2015-06-01' 
, FNPRICE DECIMAL(10, 2) NOT NULL DEFAULT 0.00
, FCPLACE VARCHAR(100) NULL
, FCGENERALLOCATION VARCHAR(100) NULL 
, FCSECURE VARCHAR(100) NULL
, FCSTART VARCHAR(100) NULL
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRIMARY KEY ( FIIDASSET ) );

ALTER TABLE ICSDB.TAICSASSET ADD CONSTRAINT TAICSASSET_FK1 FOREIGN KEY ( FIIDLEDGER, FCSUBCLASS )
 REFERENCES ICSDB.CTICSLEDGER ( FIIDLEDGER,  FCSUBCLASS );

CREATE UNIQUE INDEX TAICSASSET_INDEX1 ON ICSDB.TAICSASSET ( FIIDASSET ASC);

CREATE INDEX TAICSASSET_INDEX2 ON ICSDB.TAICSASSET ( FIIDLEDGER ASC, FCSUBCLASS ASC);

CREATE UNIQUE INDEX TAICSASSET_INDEX3 ON ICSDB.TAICSASSET ( FITAG ASC);

create user 'ICS_PORTAL_USER'@'localhost' IDENTIFIED BY 'p0rt4l_us3r';

GRANT SELECT, INSERT, UPDATE, DELETE ON ICSDB.TAICSUSER TO ICS_PORTAL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ICSDB.TAICSASSET TO ICS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON ICSDB.CTICSLEDGER TO ICS_PORTAL_USER;
GRANT SELECT, DELETE, UPDATE, INSERT ON ICSDB.CTICSPROPERTY TO ICS_PORTAL_USER;
