DROP TABLE CISDB.CTCISMATERIAL;

CREATE TABLE CISDB.CTCISMATERIAL 
( 
  FIIDMATERIAL INT(3) NOT NULL AUTO_INCREMENT
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRIMARY KEY ( FIIDMATERIAL ) );

CREATE INDEX CTCISMATERIAL_INDEX1 ON CISDB.CTCISMATERIAL ( FIIDMATERIAL);
