DROP TABLE CISDB.CTCISCOLOR ;

CREATE TABLE CISDB.CTCISCOLOR 
( 
  FIIDCOLOR INT(3) NOT NULL AUTO_INCREMENT
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRIMARY KEY ( FIIDCOLOR ) );

CREATE INDEX CTCISCOLOR_INDEX1 ON CISDB.CTCISCOLOR ( FIIDCOLOR ASC);

