DROP TABLE CISDB.CTCISLEDGER;

CREATE TABLE CISDB.CTCISLEDGER 
( 
  FIIDLEDGER INT(10) NOT NULL 
, FCSUBCLASS VARCHAR(2) NOT NULL 
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDLEDGER, FCSUBCLASS ) );

CREATE INDEX CTCISLEDGER_INDEX1 ON CISDB.CTCISLEDGER ( FIIDLEDGER ASC, FCSUBCLASS ASC);
