DROP TABLE CISDB.CTCISPROPERTY;

CREATE TABLE CISDB.CTCISPROPERTY 
( 
  FCIDPROPERTY VARCHAR(30) NOT NULL
, FCVALUE VARCHAR(50) NOT NULL
, CONSTRAINT PRIMARY KEY ( FCIDPROPERTY ) );

CREATE INDEX CTCISPROPERTY_INDEX1 ON CISDB.CTCISPROPERTY ( FCIDPROPERTY ASC);