CREATE TABLE CTCISROLE (
  FIIDROLE int(3) NOT NULL AUTO_INCREMENT,
  FCROLE varchar(100) NOT NULL,
  FCDESCRIPTION varchar(100) NOT NULL,
  FDREGISTERDATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FDLASTUPDATE timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY (FIIDROLE)
)

CREATE INDEX CTCISROLE_INDEX1 ON CISDB.CTCISROLE ( FIIDROLE ASC);