--DROP TABLE ICSDB.CTICSPROPERTY;

CREATE TABLE ICSDB.CTICSPROPERTY 
( 
  FCIDPROPERTY VARCHAR(30) NOT NULL
, FCVALUE VARCHAR(50) NOT NULL
, FCDEFAULT VARCHAR(50) NOT NULL 
, CONSTRAINT PRIMARY KEY ( FCIDPROPERTY ) );

CREATE INDEX CTICSPROPERTY_INDEX1 ON ICSDB.CTICSPROPERTY ( FCIDPROPERTY ASC);