--DROP TABLE ICSDB.CTICSLEDGER;

CREATE TABLE ICSDB.CTICSLEDGER 
( 
  FIIDLEDGER INT(10) NOT NULL 
, FCSUBCLASS VARCHAR(2) NOT NULL 
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDLEDGER, FCSUBCLASS ) );

CREATE INDEX CTICSLEDGER_INDEX1 ON ICSDB.CTICSLEDGER ( FIIDLEDGER ASC, FCSUBCLASS ASC);