DROP TABLE CISDB.TACISUSER;

CREATE TABLE CISDB.TACISUSER 
( 
  FIIDUSER INT(10) NOT NULL AUTO_INCREMENT
, FCUSERNAME VARCHAR(50) NOT NULL  
, FCPASSWORD VARCHAR(100) NOT NULL 
, FCAUTHORITY VARCHAR(50) NOT NULL 
, FCENABLED ENUM('1','0') NOT NULL  
, FCNAME VARCHAR(50) NOT NULL  
, FCLASTNAME VARCHAR(50)  
, FCSEX ENUM('M','F')  
, FDBIRTH DATE  
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDUSER ) );

CREATE UNIQUE INDEX TACISUSER_INDEX1 ON CISDB.TACISUSER ( FIIDUSER ASC);

CREATE UNIQUE INDEX TACISUSER_INDEX2 ON CISDB.TACISUSER ( FCUSERNAME ASC);
