--DROP TABLE ICSDB.TAICSASSET;

CREATE TABLE ICSDB.TAICSASSET 
( 
  FIIDASSET BIGINT(19) NOT NULL AUTO_INCREMENT
, FIIDLEDGER INT(10) NOT NULL 
, FCSUBCLASS VARCHAR(2) NOT NULL 
, FCDESCRIPTION VARCHAR(100) NOT NULL 
, FCBRAND VARCHAR(100) NULL DEFAULT 'Sin marca' 
, FCMODEL VARCHAR(100) NULL DEFAULT 'Sin modelo' 
, FCSERIALNUMBER VARCHAR(100) NULL DEFAULT 'Sin numero de serie' 
, FCMATERIAL VARCHAR(100) NULL 
, FCCOLOR VARCHAR(100) NULL 
, FCSUPPLIER VARCHAR(100) NULL DEFAULT 'Proveedor no identificado' 
, FCGENERALMANAGER VARCHAR(100) NULL 
, FCDIRECTLYRESPONSIBLE VARCHAR(100) NULL 
, FITAG BIGINT(19) NOT NULL 
, FCBILL VARCHAR(100) NULL DEFAULT 'Sin factura' 
, FDBILLINGDATE DATE NULL DEFAULT '2015-06-01' 
, FCLOCATION VARCHAR(100) NULL 
, FDUSEDATE DATE NULL DEFAULT '2015-06-01' 
, FNPRICE DECIMAL(10, 2) NOT NULL DEFAULT 0.00
, FCPLACE VARCHAR(100) NULL
, FCGENERALLOCATION VARCHAR(100) NULL 
, FCSECURE VARCHAR(100) NULL
, FCSTART VARCHAR(100) NULL
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, CONSTRAINT PRIMARY KEY ( FIIDASSET ) );

ALTER TABLE ICSDB.TAICSASSET ADD CONSTRAINT TAICSASSET_FK1 FOREIGN KEY ( FIIDLEDGER, FCSUBCLASS )
 REFERENCES ICSDB.CTICSLEDGER ( FIIDLEDGER,  FCSUBCLASS );

CREATE UNIQUE INDEX TAICSASSET_INDEX1 ON ICSDB.TAICSASSET ( FIIDASSET ASC);

CREATE INDEX TAICSASSET_INDEX2 ON ICSDB.TAICSASSET ( FIIDLEDGER ASC, FCSUBCLASS ASC);

CREATE UNIQUE INDEX TAICSASSET_INDEX3 ON ICSDB.TAICSASSET ( FITAG ASC);