--DROP TABLE ICSDB.TAICSUSER;

CREATE TABLE ICSDB.TAICSUSER 
( 
  FIIDUSER INT(10) NOT NULL AUTO_INCREMENT
, FCUSERNAME VARCHAR(50) NOT NULL  
, FCPASSWORD VARCHAR(100) NOT NULL 
, FCAUTHORITY VARCHAR(50) NOT NULL 
, FCENABLED ENUM('1','0') NOT NULL  
, FCNAME VARCHAR(50) NOT NULL  
, FCLASTNAME VARCHAR(50)  
, FCSEX ENUM('M','F')  
, FDBIRTH DATE  
, FDREGISTERDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, FDLASTUPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, CONSTRAINT PRIMARY KEY ( FIIDUSER ) );

CREATE UNIQUE INDEX TAICSUSER_INDEX1 ON ICSDB.TAICSUSER ( FIIDUSER ASC);

CREATE UNIQUE INDEX TAICSUSER_INDEX2 ON ICSDB.TAICSUSER ( FCUSERNAME ASC);