INSERT INTO CISDB.CTCISASSETTYPE (FIIDASSETTYPE, FCSUBCLASS, FCDESCRIPTION) values (514, '01', 'SILLA');
INSERT INTO CISDB.CTCISASSETTYPE (FIIDASSETTYPE, FCSUBCLASS, FCDESCRIPTION) values (514, '02', 'MESA');
INSERT INTO CISDB.CTCISASSETTYPE (FIIDASSETTYPE, FCSUBCLASS, FCDESCRIPTION) values (514, '03', 'PIZARRON');
INSERT INTO CISDB.CTCISASSETTYPE (FIIDASSETTYPE, FCSUBCLASS, FCDESCRIPTION) values (514, '04', 'BORRADOR');