
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (511,'01','SILLA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (511,'02','MESA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (511,'03','PIZARRON');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (511,'04','BORRADOR');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (512,'01','SILLA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (512,'02','MESA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (512,'03','PIZARRON');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (512,'04','BORRADOR');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (513,'01','SILLA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (513,'02','MESA');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (513,'03','PIZARRON');
Insert into CISDB.CTCISLEDGER (FIIDLEDGER,FCSUBCLASS,FCDESCRIPTION) values (513,'04','BORRADOR');
