INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('OTRO');
INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('MUEBLE');
INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('ELECTRONICO');
INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('AUTO');
INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('MATERIAL');
INSERT INTO CISDB.CTCISASSETTYPE (FCDESCRIPTION) values ('COMPUTO');